version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rockbroker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=rockbroker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    ports:
      - '5432:5432'
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  database-volume:
    driver: local


# Until the frontend dir is built...
#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend